version: '3.7'
services:
  codecept:
    image: codeception/codeception:latest
    dns: 8.8.4.4
    depends_on:
      - chrome
    volumes:
      - .:/project
  chrome:
    ports:
      - '4444'
      - '5901:5900'
    dns: 8.8.4.4
    image: selenium/standalone-chrome-debug:latest